name: build

on:

  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: dotnet restore

    - name: Build debug
      run: dotnet build -c Debug --no-restore

    - name: Test
      run: dotnet test -c Debug --no-restore --no-build --verbosity normal

    - name: Build release
      run: dotnet build -c Release --no-restore

    - name: Create NuGet
      run: dotnet pack -c Release --no-restore --no-build

    - name: Create Zip
      run: |
        dotnet publish -c Release --no-restore --no-build
        dotnet publish -r win-x64 -c Release
        cp LICENSE artifacts/bin/win-x64/publish/beefctl.exe artifacts/bin/publish
        (cd artifacts/bin/publish && 7z a -mx9 ../beefctl.zip *)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: beefweb_dotnet
        if-no-files-found: error
        path: |
          artifacts/bin/*.nupkg
          artifacts/bin/*.zip
